# Generated by Django 3.0.6 on 2020-05-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotate_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
